apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-api-app
  labels:
    app: helios-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios-api-app
  template:
    metadata:
      labels:
        app: helios-api-app
    spec:
      containers:
        - name: helios-api-app
          image: asia-southeast1-docker.pkg.dev/celtic-sunlight-419307/helios-api/helios-api:latest
          envFrom:
            - configMapRef:
                name: helios-api-config
          ports:
            - containerPort: 8080
