apiVersion: v1
kind: Service
metadata:
  name: helios-api-app-service
spec:
  selector:
    app: helios-api-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
  type: LoadBalancer
